# Generated by Django 5.0.3 on 2024-03-10 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
                ('role', models.CharField(blank=True, choices=[('main', 'Main'), ('other', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OtherUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_region', models.CharField(blank=True, max_length=30, null=True)),
                ('service', models.CharField(blank=True, choices=[('mis', 'Mis'), ('tfoms', 'Tfoms')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='RegionsAndUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('region', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.regions')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.otheruser')),
            ],
        ),
    ]
