# Generated by Django 5.0.3 on 2024-03-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regions',
            new_name='Region',
        ),
        migrations.RenameModel(
            old_name='RegionsAndUsers',
            new_name='RegionsAndUser',
        ),
        migrations.AlterModelOptions(
            name='generaluser',
            options={'verbose_name': 'Основные пользователя чата', 'verbose_name_plural': 'Основные пользователи чата'},
        ),
        migrations.AlterModelOptions(
            name='otheruser',
            options={'verbose_name': 'Пользователь региона', 'verbose_name_plural': 'Пользователи региона'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
        migrations.AlterModelOptions(
            name='regionsanduser',
            options={'verbose_name': 'Регионы и пользователи', 'verbose_name_plural': 'Регионы и пользователи'},
        ),
    ]
