# Generated by Django 5.0.3 on 2024-03-10 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_otheruser_options_region_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='users',
        ),
        migrations.CreateModel(
            name='RegionsAndUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ чата')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.region', verbose_name='Регион')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.otheruser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регион и пользователь',
                'verbose_name_plural': 'Регионы и пользователи',
            },
        ),
    ]
