# Generated by Django 5.0.3 on 2024-03-19 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_generaluser_name_alter_generaluser_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaluser',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Основные пользователи чата'},
        ),
        migrations.AlterModelOptions(
            name='otheruser',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Маршрутная карта'},
        ),
        migrations.AlterField(
            model_name='generaluser',
            name='role',
            field=models.CharField(blank=True, choices=[('MAIN', 'Основной чат'), ('MINI', 'Мини чат')], max_length=10, verbose_name='Тип чата'),
        ),
        migrations.AlterField(
            model_name='region',
            name='service',
            field=models.CharField(blank=True, choices=[('MIS', 'МИС'), ('TFOMS', 'ТФОМС')], max_length=7, verbose_name='Сервис'),
        ),
        migrations.AlterField(
            model_name='regionsandusers',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.otheruser', verbose_name='Юзернейм'),
        ),
    ]
